/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Supabase configuration - load from environment variables
export const projectId = import.meta.env.VITE_SUPABASE_URL?.replace('https://', '').replace('.supabase.co', '') || 'wobnatxxuiiqjpyufghs';
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvYm5hdHh4dWlpcWpweXVmZ2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjI3MzIsImV4cCI6MjA3MTUzODczMn0.l71d4-xrFn-XNyb7iCBoT78NVY5FoDXhjbfJbwsH_3E';

// Construct the full Supabase URL
export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || `https://${projectId}.supabase.co`;

// Storage configuration
export const storageUrl = import.meta.env.VITE_SUPABASE_STORAGE_URL || `${supabaseUrl}/storage/v1`;

// Frontend URL for auth redirects
export const frontendUrl = import.meta.env.VITE_FRONTEND_URL || 'http://localhost:3000';